"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-audit' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
# Regenerated 2026-06-07 for ADR-0001 W1: scitex_security removed
# (absorbed into scitex_audit.github); scitex_audit + scitex_audit.cli
# added so the gate sees the self-imports introduced by the new public
# submodule + CLI surface.
CROSS_PACKAGE_IMPORTS = [
    "scitex_audit",
    "scitex_audit.cli",
    "scitex_dev._cli._completion",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_declared_cross_package_dependency_imports_successfully(module_name):
    """Importing scitex-audit's declared cross-package dependency must succeed."""
    # Arrange
    target_module_name = module_name
    # Act
    imported = pytest.importorskip(target_module_name)
    # Assert
    assert imported is not None
