"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def _run_audit_all_for_scitex_audit():
    """Helper that runs audit-all and returns True on success."""
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package("scitex-audit")
    return True


def test_audit_all_runs_clean_for_scitex_audit():
    # Arrange
    target_package = "scitex-audit"
    # Act
    completed = _run_audit_all_for_scitex_audit()
    # Assert
    assert completed is True, f"audit-all failed for {target_package}"
